### PR TITLE
Add the 'ode' type to the list.

### PR DESCRIPTION
**Pull request by luciansmith**
We renamed all .xpp files to .ode in the biomodels project, so we need to now recognize those files.

### CODE REVIEW

**Comment by luciansmith** [comment]
@jonrkarr : Can we merge this?  I need this one to run the latest temp_biomodels github actions, since we've renamed '.xpp' to '.ode', and need to create appropriate combine archive index files from them.  Thanks!

**Comment by jonrkarr** [comment]
I don't have strong preferences for these URIs because I'd prefer to see them all replaced by URIs for EDAM terms, as these aren't registered or commonly recognized media types. Unfortunately, that's still waiting on the EDAM developers to approve my PRs.

This would break what the XPP interface is set up to recognize. I added something on top to avoid needing to change the archives we already have. Basically, this allows `ode` or `xpp` to be used interchangeably in URIs. For example, ModelDB mainly uses the `ode` extension, but sometimes uses `xpp`. 

@luciansmith does this look good to you?

**Comment by luciansmith** [comment]
That works for me!  I just needed something to work with files named [x].ode, since that's what we renamed everything to.

**Comment by luciansmith** [comment]
@jonrkarr : Can you release a version of biosimulators_utils that has this change in it?  I need it to run the latest temp_biomodels.  Thanks!  (The other change just reduces the warnings; it would be nice, but doesn't block anything like this does.)

**Comment by jonrkarr** [comment]
This should be released at 0.1.169 in a few minutes. 

The release protocol is:
- Update the version number in `biosimulators_utils/_version.py`
- Commit and push this change
- Add a Git tag with the version
- Push the new Git tag

The last step will trigger a GitHub action to create a new GitHub release and push a new version to PyPI.

**Pull request merged**
