### PR TITLE
feat: check all SED-ML XPath targets and warn appropriately

### PR DESCRIPTION
**Pull request by luciansmith**
This was part of the earlier change but somehow got dropped.

EDIT:  fundamental changes due to comments; see below.

### CODE REVIEW

**Comment by jonrkarr** [comment]
I removed this because such attribute changes can also make changes that can break other XPaths. While this might not be the typical use pattern, this is possible. More nuanced analysis is needed to evaluate this.

**Comment by jonrkarr** [comment]
Basically, every change should be considered a "structural" change. This is one of the insidious features of XPaths. For many reasons, I'd advocate L2 SED-ML use something else.

**Comment by luciansmith** [comment]
OK, in that case I think we should validate the XPaths but put in warnings instead.  Not validating the XPaths at all seems like a waste.  (And again, I'm getting pages and pages of 'didn't check this xpath; didn't check the other xpath', which is not very helpful.)

**Comment by jonrkarr** [comment]
The XPaths are still validated and a warning is generated
- Adhere to valid XML XPath syntax
- Namespaces in the XPath are defined

**Comment by jonrkarr** [comment]
Could you add unit tests which illustrate the cases this impacts?

**Comment by jonrkarr** [comment]
@luciansmith it looks like you're still working on this. I converted this to draft so I know not to merge this yet. When its ready, click the "Ready for review" button below.

**Comment by luciansmith** [comment]
OK!  Major update that fundamentally changes the goal of this pull request.  See https://github.com/biosimulators/Biosimulators_utils/pull/102/commits/e72edd4bf667dc3a0ac03586accc384da195da90 for details, but in general:  given that attribute changes can make XPaths valid or invalid, we just acknowledge this everywhere, and validate targets anyway.

**Comment by luciansmith** [comment]
Sure, adding tests is a good idea.

**Comment by jonrkarr** [comment]
Because this can lead to the false identification of errors, such issues should be reported as warnings. An additional option (whose default value is OFF) could be added to report them as errors.

**Comment by luciansmith** [comment]
Correct!  XPath validation errors are only treated as errors if there are no model changes.  See https://github.com/biosimulators/Biosimulators_utils/blob/check-datagens/biosimulators_utils/sedml/validation.py#L1659

**Comment by jonrkarr** [comment]
That works. This should help close the remaining gap in the validation of the SED-ML files from BioModels.

**Comment by luciansmith** [comment]
I'm having a little trouble figuring out how best to fit the design of your unit test system.  I have some SED-ML files that should each produce a different suite of errors and warnings, but I'm not sure how best to wrap them into your system.  Should the SED-ML of each be created from scratch?  Should I load just one and make changes to create the others internally?  Should I just save all four and load them?

[four_sedml_files.zip](https://github.com/biosimulators/Biosimulators_utils/files/8137420/four_sedml_files.zip)

The results should be:

No change, good xpath:  no errors, no warnings
No change, bad xpath:  error for bad xpath, no warnings
Change, good xpath:  no errors, one general 'xpaths might be bad' warning.
Change, bad xpath:  no errors, one 'xpaths might be bad' warning, and one 'the xpath is bad but might be fixed by change' warning.

I also feel like xpaths for elements other than data generators should be tested in the presence/absence of a model change, but figured the datagens could be first.

**Comment by jonrkarr** [comment]
The SED-ML can either be generated in the code, or it could saved to the repository in `tests/fixtures`.

**Comment by jonrkarr** [comment]
The new test cases can be added to `tests/sedml/test_sedml_validation.py`, or you could start a new file in the same directory.

**Comment by luciansmith** [comment]
OK!  I'll do that, then.

**Comment by luciansmith** [comment]
This should be good to go!

**Review by jonrkarr — APPROVED** [review]

**Comment by jonrkarr** [comment]
Will be released as `0.1.170` in a few minutes.

**Pull request merged**
