### PR TITLE
fix: change exception "type" to "category" 

### PR DESCRIPTION
**Pull request by bilalshaikh42**
adressess https://github.com/biosimulations/biosimulations/issues/3482

### CODE REVIEW

**Comment by bilalshaikh42** [comment]
@all-contributors add @bilalshaikh42 for code, ideas

**Comment by jonrkarr** [comment]
@

**Comment by jonrkarr** [comment]
Please undo this change. The data model has been corrected in biosimulations.

**Comment by jonrkarr** [comment]
Nevermind. I see this wasn't merged.

**Pull request closed without merging**
